### ISSUE TITLE
JS / CSS style guide and testing

### ISSUE THREAD

**Issue by alex-bu-89** [tuicom/tmp-6m-specs#1]
Hi @lxg,
I have a few minor questions regarding the 6m specs.

1) Is any JS / CSS style guides already discussed or I did miss something? 
Some linter for instance or similar. Could it be important? I can imagine, that we'll have a bunch of reusable components with different code rules/styles/formats etc., that in my opinion is not so nice. Or it will depend only on teams? Like, what the team prefers?

2) And what about testing? Should components be unit / e2e tested? Could it be implemented in build pipeline as well? Should we have any specs about it?

What do u think?
Thanks.

**Comment by lxg** [comment]
Hi,

Thanks for your feedback! Regarding your questions:

- There is no styleguide for JS, especially as we leave the choice of framework to the component maintainer. It is encouraged to follow the style guide of the framework, or apply common best practice. But it might indeed be a good idea to point this out in the specs.

- As for CSS, we (i.e. mostly the UX team) are still discussing the CSS stragegy. You know, the classic Common Style Provider vs. a modular one, also scoped CSS and vs. BEM notation. I would love to put more information about CSS into the 6M specs, but for now there is nothing settled in this area, as far as I know.

- I would also love to see more specific requirements regarding unit and e2e testing, and I agree there should be more details about this in the spec. That being said, testing depends on a few things which are beyond the scope of the spec: the framework used, the requirements from the PO, the degree of test coverage that makes sense for the particular component (e.g. a security-sensitive component may need different testing than a more simple one). I think this is more of a topic for the particular product’s/team’s Definition of Done.

I will take these points into consideration and bring them up in the discussions. Thanks again!

**Comment by alex-bu-89** [comment]
Alrighty, thank you. 👍
